/**
 * Generated by [gradle-kotlin-dsl-libs](https://github.com/jmfayard/gradle-kotlin-dsl-libs)
 *
 * Run again
 *   `$ ./gradlew syncLibs`
 * to update this file */
object Libs {
    /**
     * [adapter-rxjava2 website](https://github.com/square/retrofit/) */
    const val adapter_rxjava2: String =
            "com.squareup.retrofit2:adapter-rxjava2:" + Versions.adapter_rxjava2

    const val com_gradle_build_scan_gradle_plugin: String =
            "com.gradle.build-scan:com.gradle.build-scan.gradle.plugin:" + Versions.com_gradle_build_scan_gradle_plugin

    /**
     * [controlsfx website](http://www.controlsfx.org/) */
    const val controlsfx: String = "org.controlsfx:controlsfx:" + Versions.controlsfx

    /**
     * [converter-moshi website](https://github.com/square/retrofit/) */
    const val converter_moshi: String =
            "com.squareup.retrofit2:converter-moshi:" + Versions.converter_moshi

    /**
     * [docopt website](https://github.com/docopt/docopt.java) */
    const val docopt: String = "com.offbytwo:docopt:" + Versions.docopt

    const val exposed: String = "org.jetbrains.exposed:exposed:" + Versions.exposed

    /**
     * [fontawesomefx website](http://www.jensd.de) */
    const val fontawesomefx: String = "de.jensd:fontawesomefx:" + Versions.fontawesomefx

    /**
     * [jdom website](http://www.jdom.org) */
    const val jdom: String = "org.jdom:jdom:" + Versions.jdom

    const val jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin: String =
            "jmfayard.github.io.gradle-kotlin-dsl-libs:jmfayard.github.io.gradle-kotlin-dsl-libs.gradle.plugin:" + Versions.jmfayard_github_io_gradle_kotlin_dsl_libs_gradle_plugin

    /**
     * [joda-time website](http://www.joda.org/joda-time/) */
    const val joda_time: String = "joda-time:joda-time:" + Versions.joda_time

    /**
     * [jsr305 website](http://findbugs.sourceforge.net/) */
    const val jsr305: String = "com.google.code.findbugs:jsr305:" + Versions.jsr305

    /**
     * [jtwig-core website](http://jtwig.org) */
    const val jtwig_core: String = "org.jtwig:jtwig-core:" + Versions.jtwig_core

    /**
     * [junit website](http://junit.org) */
    const val junit: String = "junit:junit:" + Versions.junit

    const val koin_core: String = "org.koin:koin-core:" + Versions.koin_core

    /**
     * [konfig website](https://github.com/npryce/konfig) */
    const val konfig: String = "com.natpryce:konfig:" + Versions.konfig

    /**
     * [kotlin-coroutines-retrofit website](https://github.com/gildor/kotlin-coroutines-retrofit) */
    const val kotlin_coroutines_retrofit: String =
            "ru.gildor.coroutines:kotlin-coroutines-retrofit:" + Versions.kotlin_coroutines_retrofit

    /**
     * [kotlin-reflect website](https://kotlinlang.org/) */
    const val kotlin_reflect: String =
            "org.jetbrains.kotlin:kotlin-reflect:" + Versions.kotlin_reflect

    /**
     * [kotlin-scripting-compiler-embeddable website](https://kotlinlang.org/) */
    const val kotlin_scripting_compiler_embeddable: String =
            "org.jetbrains.kotlin:kotlin-scripting-compiler-embeddable:" + Versions.kotlin_scripting_compiler_embeddable

    /**
     * [kotlin-stdlib-jdk8 website](https://kotlinlang.org/) */
    const val kotlin_stdlib_jdk8: String =
            "org.jetbrains.kotlin:kotlin-stdlib-jdk8:" + Versions.kotlin_stdlib_jdk8

    /**
     * [kotlin-test website](https://kotlinlang.org/) */
    const val kotlin_test: String = "org.jetbrains.kotlin:kotlin-test:" + Versions.kotlin_test

    /**
     * [kotlin-test-junit website](https://kotlinlang.org/) */
    const val kotlin_test_junit: String =
            "org.jetbrains.kotlin:kotlin-test-junit:" + Versions.kotlin_test_junit

    /**
     * [kotlinpoet website](http://github.com/square/kotlinpoet/) */
    const val kotlinpoet: String = "com.squareup:kotlinpoet:" + Versions.kotlinpoet

    /**
     * [kotlintest website](http://www.github.com/kotlintest/kotlintest) */
    const val kotlintest: String = "io.kotlintest:kotlintest:" + Versions.kotlintest

    /**
     * [kotlinx-coroutines-core website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_core: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-core:" + Versions.kotlinx_coroutines_core

    /**
     * [kotlinx-coroutines-rx2 website](https://github.com/Kotlin/kotlinx.coroutines) */
    const val kotlinx_coroutines_rx2: String =
            "org.jetbrains.kotlinx:kotlinx-coroutines-rx2:" + Versions.kotlinx_coroutines_rx2

    /**
     * [kotlinx-html-jvm website](https://github.com/Kotlin/kotlinx.html) */
    const val kotlinx_html_jvm: String =
            "org.jetbrains.kotlinx:kotlinx-html-jvm:" + Versions.kotlinx_html_jvm

    const val krangl: String = "de.mpicbg.scicomp:krangl:" + Versions.krangl

    /**
     * [logging-interceptor website](https://github.com/square/okhttp) */
    const val logging_interceptor: String =
            "com.squareup.okhttp3:logging-interceptor:" + Versions.logging_interceptor

    /**
     * [mockito-core website](https://github.com/mockito/mockito) */
    const val mockito_core: String = "org.mockito:mockito-core:" + Versions.mockito_core

    /**
     * [mockito-kotlin website](https://github.com/nhaarman/mockito-kotlin) */
    const val mockito_kotlin: String = "com.nhaarman:mockito-kotlin:" + Versions.mockito_kotlin

    /**
     * [mockwebserver website](https://github.com/square/okhttp) */
    const val mockwebserver: String = "com.squareup.okhttp3:mockwebserver:" + Versions.mockwebserver

    /**
     * [moshi website](https://github.com/square/moshi) */
    const val moshi: String = "com.squareup.moshi:moshi:" + Versions.moshi

    /**
     * [moshi-lazy-adapters website](https://github.com/serj-lotutovici/moshi-lazy-adapters/) */
    const val moshi_lazy_adapters: String =
            "com.serjltt.moshi:moshi-lazy-adapters:" + Versions.moshi_lazy_adapters

    /**
     * [okhttp website](https://github.com/square/okhttp) */
    const val okhttp: String = "com.squareup.okhttp3:okhttp:" + Versions.okhttp

    /**
     * [okio website](https://github.com/square/okio/) */
    const val okio: String = "com.squareup.okio:okio:" + Versions.okio

    const val org_jetbrains_kotlin_jvm_gradle_plugin: String =
            "org.jetbrains.kotlin.jvm:org.jetbrains.kotlin.jvm.gradle.plugin:" + Versions.org_jetbrains_kotlin_jvm_gradle_plugin

    /**
     * [postgresql website](https://github.com/pgjdbc/pgjdbc) */
    const val postgresql: String = "org.postgresql:postgresql:" + Versions.postgresql

    /**
     * [retrofit website](https://github.com/square/retrofit/) */
    const val retrofit: String = "com.squareup.retrofit2:retrofit:" + Versions.retrofit

    /**
     * [retrofit-mock website](https://github.com/square/retrofit/) */
    const val retrofit_mock: String =
            "com.squareup.retrofit2:retrofit-mock:" + Versions.retrofit_mock

    /**
     * [rxjava website](https://github.com/ReactiveX/RxJava) */
    const val rxjava: String = "io.reactivex.rxjava2:rxjava:" + Versions.rxjava

    /**
     * [rxkotlin website](https://github.com/ReactiveX/RxKotlin) */
    const val rxkotlin: String = "io.reactivex.rxjava2:rxkotlin:" + Versions.rxkotlin

    /**
     * [selenium-java website](http://www.seleniumhq.org/) */
    const val selenium_java: String =
            "org.seleniumhq.selenium:selenium-java:" + Versions.selenium_java

    /**
     * [slf4j-simple website](http://www.slf4j.org) */
    const val slf4j_simple: String = "org.slf4j:slf4j-simple:" + Versions.slf4j_simple

    /**
     * [timber website](https://github.com/JakeWharton/timber) */
    const val timber: String = "com.jakewharton.timber:timber:" + Versions.timber

    /**
     * [tornadofx website](https://github.com/edvin/tornadofx) */
    const val tornadofx: String = "no.tornado:tornadofx:" + Versions.tornadofx

    /**
     * [zt-exec website](https://github.com/zeroturnaround/zt-exec) */
    const val zt_exec: String = "org.zeroturnaround:zt-exec:" + Versions.zt_exec
}
