#!/usr/bin/env kotlin-script.sh
package csv2sql

import okio.BufferedSource
import okio.buffer
import okio.source
import java.io.File

fun main(args: Array<String>) {
    val file = File(args[0])

    generateSql(file.source().buffer())
}

val start = """
SET foreign_key_checks = 0;
TRUNCATE `market`;

# Generated by a kotlin script from a CSV export
INSERT INTO `market` (created_at,updated_at,deleted_at,version,name,customer_id,market_group,ecr_id,field_worker,city,street,zipcode,ceo,director,dispatcher,phone)
VALUES
"""

val end = """
;

SET foreign_key_checks = 1;
"""

val pattern = """
('2016-12-09 16:27:53','2016-12-09 16:27:53',NULL,0,'%s',%s,%s,'%s','%s','%s','%s','%s','%s','%s','%s','%s')
"""

fun generateSql(okSource: BufferedSource) {
    println(start)
    okSource.readUtf8Line()
    while (!okSource.exhausted()) {
        val line = okSource.readUtf8Line() ?: break
        val data = line.split(";").toTypedArray()
        if (data.size == 1) {
            continue
        }
        if (data.size < 12) {
            TODO("Unexpected line \n$line\n")
        }
        val output = String.format(pattern, *data).trim()
        println(output)
        if (!okSource.exhausted())
            println(",")
    }

    println(end)
}
